[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
dependencies = ["requests >= 2.28.0", "requests-toolbelt >= 1.0.0"]
name = "sploitlib"
readme = "README.md"
version = "0.1.0"
